[project]
name = "helixbio"
version = "0.3.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "biopython>=1.84",
    "loguru>=0.7.2",
    "modal>=0.64.232",
    "pandas>=2.2.3",
]
